[styleDate]
StringAlign = Left
StringCase = None
FontColor= #FontColorLow#
FontFace = #FontFamilyText#
FontSize = #FontSizeSmall#
AntiAlias = 1
ClipString = 1
H = 14
X = 30
Y = 5
W = #RightSideBarWidth#

[styleDateOpt]
StringAlign = Right
StringCase = None
FontColor= #FontColorLow#
FontFace = #FontFamilyText#
FontSize = #FontSizeSmall#
AntiAlias = 1
ClipString = 1
H = 14
X = 320
Y = 5
W = 150

[styleDesc]
StringAlign = Left
StringCase = None
SolidColor = #SolidColorTransparent#
StringEffect = Shadow
FontEffectColor = #FontEffectColorNormal#
FontColor = #FontColorHighlight#
FontFace = #FontFamilyText#
FontSize = #FontSizeMedium#
AntiAlias = 1
ClipString = 1
H = 16
X = 45
Y = 12r
W = 270

[styleCalBar]
X = 40
Y = 18
W = 3
H = 12