[styleFeedTitle]
StringAlign = Left
StringCase = None
SolidColor = #SolidColorTransparent#
FontColor= #FontColorLow#
FontFace = #FontFamilyText#
FontSize = #FontSizeBig#
AntiAlias = 1
ClipString = 1
H = 22
X = 71
Y = 5
W = (#RightSideBarWidth# - 41)

[styleFeedPages]
Text = "n"
FontColor = #FontColorLow#
FontFace = Webdings
FontSize = 7
AntiAlias = 1
Y = 226
Hidden = 1

[styleFeedContent]
SolidColor = #SolidColorTransparent#
StringEffect = Shadow
FontEffectColor = #FontEffectColorNormal#
FontColor = #FontColorHighlight#
FontFace = #FontFamilyText#
FontSize = #FontSizeMedium#
AntiAlias = 1
ClipString = 1
X = 30
Y = 35
W = #RightSideBarWidth#
H = (#MultiHeight# - 55)
Hidden = 1

[styleFeedEntryTitle]
StringAlign = Left
StringCase = None
FontColor= #FontColorHighlight#
FontFace = #FontFamilyText#
FontSize = (#FontSizeSmall# + 1)
AntiAlias = 1
ClipString = 1
H = 14
X = 30
Y = 5
W = #RightSideBarWidth#

[styleFeedEntryDesc]
StringAlign = Left
StringCase = None
SolidColor = #SolidColorTransparent#
StringEffect = Shadow
FontEffectColor = #FontEffectColorNormal#
FontColor = #FontColorLow#
FontFace = #FontFamilyText#
FontSize = #FontSizeMedium#
AntiAlias = 1
ClipString = 1
H = 16
X = 45
Y = 12r
W = 270

[styleFeedIcon]
MouseActionCursor = 1
Greyscale = 1
W = 14
H = 14
Y = 9