[styleTitle]
StringAlign = Center
SolidColor = #SolidColorTransparent#
StringCase = Upper
StringStyle = Bold
FontColor = #FontColorTitle#
FontFace = #FontFamilyTitle#
FontSize = #FontSizeBig#
MouseActionCursor = 1
Angle = 1.57
AntiAlias = 1
ClipString = 1
X = 20
Y = 122
W = 100
H = 18

[styleSeperator]
SolidColor = #SolidColorSeperator#
X = 30
W = #RightSideBarWidth#
H = 2

[styleBar]
BarColor = #BarColorHighlight#
BarOrientation = Horizontal
SolidColor = #BarColorLow#
X = 30
Y = 0R
W = 290
H = #BarHeight#

[styleIcon]
X = 270r
Y = -16r
W = 16
H = 16

[styleLeftText]
StringAlign = Left
StringCase = None
StringEffect = Shadow
FontEffectColor=0,0,0,20
FontColor=#FontColorLow#
FontSize=#FontSizeSmall#
AntiAlias=1
ClipString=1
X=30
Y=18
W=290
H=14

[styleRightText]
StringAlign=RIGHT
StringCase=NONE
StringEffect=SHADOW
FontEffectColor=0,0,0,20
FontColor=FFFFFF
FontSize=#FontSizeSmall#
AntiAlias=1
ClipString=1
X=295
Y=0r
W=290
H=14