[Variables]
; Private GCal Adresses up to 4 Adresses
EventURL1 = https://www.google.com/calendar/feeds/7ibhtmaefappftac00g2702j68%40group.calendar.google.com/private-88ffef7aeb85fdfc246fa140414004c9/basic?max-results=8&futureevents=true&singleevents=true&orderby=starttime&sortorder=a
EventURL2 = https://www.google.com/calendar/feeds/maikefiege%40googlemail.com/private-50bcd20b6cca19dfd3616b6e3618fe12/basic?max-results=8&futureevents=true&singleevents=true&orderby=starttime&sortorder=a
EventURL3 = https://www.google.com/calendar/feeds/badhard.ba%40googlemail.com/private-d8255c7950dc68519ebb1a5565191e52/basic?max-results=8&futureevents=true&singleevents=true&orderby=starttime&sortorder=a
EventURL4 = https://www.google.com/calendar/feeds/hp8m4q16h1fmevv1dum8hjq9dg%40group.calendar.google.com/private-7a0dba09af55de9c31f229e4c773dd9c/basic?max-results=8&futureevents=true&singleevents=true&orderby=starttime&sortorder=a

EventFontColorToday = 255,255,255,255
EventFontColorTomorrow = 255,255,255,255

EventBarColor1 = 25,162,222,255
EventBarColor2 = 25,162,222,100
EventBarColor3 = 230,93,33,255
EventBarColor4 = 230,93,33,100
