[Variables]
; Every 300 Seconds = 5 Mins the Plugin updates itself
UpdateRate = 300

; Position+
RightSideBarWidth = 290

; ============================================================
; Font
; ============================================================
FontFamilyTitle = Agency FB
FontFamilyText = century Gothic

FontSizeSmall = 8
FontSizeMedium = 9
FontSizeBig = 14

SolidColorSeperator = 225,225,225,35
SolidColorTransparent = 0,0,0,1

FontColorTitle = 255,255,255,255

FontColorHighlight = 255,255,255,255
FontColorLow = 170,170,170,255
FontEffectColorNormal = 0,0,0,20