[Variables]
PaperBackgroundX2 = 1280
PaperBackgroundY2 = 800

PaperFrontgroundX1 = 150

PaperFrontBackPadding = 10

PaperRoundRadius = 10
PaperRoundDiameter = (2 * #PaperRoundRadius#)

PaperRows = 5
PaperCols = 4

PaperEntryWidth = (#BackgroundX2# - #FrontgroundX1# - #FrontBackPadding# - 2*#PaperRoundRadius# - (#PaperCols# - 1)*#PaperRoundRadius#)/#PaperCols#
PaperEntryHeight = (#BackgroundY2# - 2*#FrontBackPadding# - 2*#PaperRoundRadius# - (#PaperRows# - 1) * #PaperRoundRadius#)/#PaperRows#

curFeed = http://www.spiegel.de/schlagzeilen/tops/index.rss
currFeedNum = 5

Feed1 = Spiegel | http://www.spiegel.de/schlagzeilen/tops/index.rss
Feed2 = HNA | http://www.hna.de/nachrichten/lokales/uslar-solling/rssfeed.rdf
Feed3 = Armorgames | http://feeds.armorgames.com/armorgames/new-games?format=xml
Feed4 = Kurz in Küche | http://mal-kurz-in-der-kueche.blogspot.com/feeds/posts/default
Feed5 = Rheinische Post | http://feeds.rp-online.de/rp-online/rss/topnews
Feed6 = Annie's Eats | http://feeds.feedburner.com/AnniesEats
Feed7 = Die kleine Küche | http://diekleinekueche.blogspot.com/feeds/posts/default
Feed8 = eat this! | http://feeds.feedburner.com/eatthisvegan
Feed9 = Französisch kochen | http://www.franzoesischkochen.de/?feed=rss2
Feed10 = Bakerella | http://feeds.feedburner.com/Bakerella
Feed11 = We love Pasta | http://www.we-love-pasta.de/feed/ 
Feed12 = Bento Bento | http://feeds.feedburner.com/BentoLunchBlog
Feed13 = Ninas Food Blog | http://feeds.feedburner.com/NinasKleinerFood-blog
Feed14 = Cooketteria | http://cooketteria.blogspot.com/feeds/posts/default
Feed15 = Kuriositätenladen | http://www.kuriositaetenladen.com/feeds/posts/default